# Generated by Django 5.0.4 on 2024-05-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_securitycard_type_vehicle_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10, null=True),
        ),
    ]
