# Generated by Django 5.0.4 on 2024-04-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_rename_content_survey_description_remove_survey_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='active',
        ),
    ]
