# Generated by Django 5.0.4 on 2024-06-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_remove_notification_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),

        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
