# Generated by Django 5.0.4 on 2024-06-11 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='order_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='pay_type',
            field=models.CharField(choices=[('momo', 'MOMO'), ('vnpay', 'VNPAY')], max_length=5, null=True),
        ),
    ]
