# Generated by Django 5.0.4 on 2024-06-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_momopaid_momolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momolink',
            name='order_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='momolink',
            name='request_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='momopaid',
            name='order_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='momopaid',
            name='request_id',
            field=models.CharField(max_length=50),
        ),
    ]
