# Generated by Django 5.0.4 on 2024-06-12 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_alter_momolink_order_id_alter_momolink_request_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VnpayPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_ref', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('order_info', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('bank_code', models.CharField(max_length=20)),
                ('bank_tran_no', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=20)),
                ('pay_date', models.BigIntegerField()),
                ('response_code', models.IntegerField()),
                ('tmn_code', models.CharField(max_length=8)),
                ('transaction_no', models.BigIntegerField()),
                ('transaction_status', models.IntegerField()),
                ('secure_hash', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VnpayLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_ref', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('order_info', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(max_length=100)),
                ('ip_addr', models.CharField(max_length=45)),
                ('payment_url', models.TextField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.payment')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.resident')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
