"""
Django settings for m_apartment_api project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tj09_a(=wy+7j@oo24#&$5l9494ijpjnumv-cm=2i^h(u-dk=4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['tnminhliem03.pythonanywhere.com']
ALLOWED_HOSTS = []

import pymysql
import stream_chat

pymysql.install_as_MySQLdb()

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apartment',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

CKEDITOR_UPLOAD_PATH = "ckeditors/images/"

AUTH_USER_MODEL = 'apartment.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'm_apartment_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'm_apartment_api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'apartment_manager_db',
        'USER': 'root',
        'PASSWORD': 'Liemkute03',
        'HOST': ''  # mặc định localhost
        # 'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'tnminhliem03$apartmentdb',
        # # 'NAME': 'apartment_manager_db_test',
        # 'USER': 'tnminhliem03',
        # 'PASSWORD': 'Liemkute03',
        # 'HOST': 'tnminhliem03.mysql.pythonanywhere-services.com'  # mặc định localhost
    }
}

import cloudinary

cloudinary.config(
    cloud_name="dr1frcopo",
    api_key="388823961895246",
    api_secret="5MZV45WmN3WZOIurHEL6r3euMvI"
)

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Local
CLIENT_ID = '4hImR9K2KtPGSj26CxHsmun8xedjHoeb9454ujur'
CLIENT_SECRET = '0zhxSJ0uJ5UTKnMdJxm6NBsh0LUX73me4QzCxaRFe5iWDIwTB6VBI6bPMQNv0rLCUZJAuWEiilI2K4EIkP3rLVey4RhjwT3iJwQEu4ZxKh89Qcicn77JgGjz7nxWDvZm'

# Pythonanywhere
CLIENT_ID = 'ixf3r8dG1ckyj2LGi9UQrLhu9cSU8cNyPIDsURrS'
CLIENT_SECRET = '5EECr7BSNWYN5oaQv6h9fyAfMOFiXcaMd5TvX0DvD0nXCujsiE4SajgkjLHMpERz2VIEYUniJJQtBx6K0COIYctCSYNeMMTHquCyuXYKZEhorV1lhbMOxgYRH82VLamU'
# OAUTH2_PROVIDER = { 'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore' }

# vnpay
VNPAY_RETURN_URL = 'http://127.0.0.1:8000/paid'  # get from config
VNPAY_PAYMENT_URL = 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html'  # get from config
VNPAY_API_URL = 'https://sandbox.vnpayment.vn/merchant_webapi/api/transaction'
VNPAY_TMN_CODE = 'BBJDENSU'  # Website ID in VNPAY System, get from config
VNPAY_HASH_SECRET_KEY = '1S8CJ30B6CNNK2G4I2A0GJ6RYKEQN966'  # Secret key for create checksum,get from config

# momo
MOMO_PARTNER_CODE = "MOMO"
MOMO_ACCESS_KEY = "F8BBA842ECF85"
MOMO_SECRET_KEY = "K951B6PE1waDMi640xX08PD3vg6EkVlz"
MOMO_RETURN_URL = "http://127.0.0.1:8000/paid"

APP_ID = 22002
APP_TOKEN = "lB3kiVHaDJJRC4NROiKcd5"